# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0482f21bbcfd37b7a75f685e81e93208993da4c3e91875948ec186961f0cdc0acaa849c1acdc0355307ccfcb768b9b743a3cfbb31bdc58e9b5fa6c9de7ad3709

test:
  secret_key_base: 5fb8dcf1a1c819d0cacf44170926d0a81a792a63f84466be8e05891f0d4002d3838a88897aecf3172d46013df0c927b7f106fa761e94fe914dd071b1012de1f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
